### ISSUE TITLE
undo and overlay tools make blender crash

### ISSUE THREAD

**Issue by doraynico** [ubisoft/shotmanager#15]
**Infos on the context**
- Add-on version: **1.6**
- Blender version, from installer or from zip: ** 2.93 from installer**
- Blender was launched in Admin mode? **no**
- OS: **win 10**
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): **yes**

**Describe the bug**
A clear and concise description of what the bug is:
**when overlays tools activated manipulate the handles of a shot in timeline and then press CRTL+Z (undo) makes Blender crash.**

**Comment by werwack** [comment]
Hi Nico,
Indeed, stability with the overlay features is a big issue at the moment, whether with undo/redo or with the loading of a new file with Overlay Tools mode activated.
I'm working on it. Should be better in the upcoming 1.6 version or SM.

**Comment by werwack** [comment]
Fixed on SM 1.6.9
