### ISSUE TITLE
Edit video is always being rendered at 1280x960

### ISSUE THREAD

**Issue by sgodanas** [ubisoft/shotmanager#18]
**Infos on the context**
- Add-on version: 1.6.9
- Blender version, from installer or from zip: 3.0.0 stable
- Blender was launched in Admin mode? no
- OS: Windows 10
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): I don't know

**Describe the bug**
My scene render resolution is set to 1920 x 1080 (in the shot manager project settings)
When I click on Render  All (with generate edit videos selected), the edit video ends up with 1280 x 960 resolution.

**Expected behavior**
The edit video resolution should be same as the shot video resolution

**Screenshots**
![image](https://user-images.githubusercontent.com/73957119/146646275-a407d399-2a9d-445c-ba82-d6aad17c0b99.png)

Thank you.

**Comment by werwack** [comment]
Hi Sgodans,
I'll check and fix asap.

**Comment by werwack** [comment]
Hi Sgodans,
The bug has been identified. A wrong _hardcoded_ resolution was used for the rendering of the take video.
This will be fixed in the next release.
Thank you for having raised the issue :)

**Comment by sgodanas** [comment]
Glad you are addressing it, Thank you!

**Comment by werwack** [comment]
Hi Sgodanas,
This has been fixed in the [version v1.7.10](https://github.com/ubisoft/shotmanager/releases/tag/v1.7.10) that has just been released.
In addition to the fix are some new options allowing you to keep the intermediate files (= original rendering and images frames from Stamp Info) and to get the renderings as image sequences as well as in videos.

**Comment by sgodanas** [comment]
Great. I have installed the latest version and before rendering I was getting TypeErrors.
Created an issue https://github.com/ubisoft/shotmanager/issues/23.

Thank you,
Satish.
