### ISSUE TITLE
Activation fail

### ISSUE THREAD

**Issue by Branskugel** [ubisoft/shotmanager#21]
**Infos on the context**
- Add-on version: 1.6.9
- Blender version, from installer: 3.0.1
- Blender was launched in Admin mode?  - No
- OS: Windows 11 x64 bit
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): No

**Describe the bug**
Blender fails to activate the addon and throws an error

**To Reproduce**
1. Try to install addon as usual
2. Click on the empty checkbox to activate, as usual
3. See error

**Expected behavior**
Successful activation

**Screenshots**
![image](https://user-images.githubusercontent.com/5613530/152675737-61fb9142-90a9-4d2d-b92d-ad3f36d80697.png)

**Comment by werwack** [comment]
Hi Branskugel,
This is a wierd bug. Do you by any chance have either [Stamp Info](https://github.com/ubisoft/stampinfo) or [Video Tracks](https://github.com/ubisoft/videotracks) installed? It is possible that a conflict exists somewhere here. Otherwise... Well, I'll investigate.
I'm about to do a new release - end of week - hopefully it should be fixed in it.

**Comment by Branskugel** [comment]
No, I do not have any of those installed but my blender config is rather custom, still I don't see any obvious sign of a conflict, but I'm no programmer

**Comment by werwack** [comment]
Hi @Branskugel ,
I tried to reproduce your installation bug and failed to face the issue.
Could you please try this:
- uninstall shot manager
- close Blender
- relaunch it in admin mode (this is very important! To do so )
- reinstall the add-on and reactivate it
At this stage it should work and you can restart Blender in normal mode for a normal use.

Let me know if that solve your problem.

Thank you

**Comment by Branskugel** [comment]
You were right. Installing it with admin privileges did work. Thank you
