### ISSUE TITLE
Shot manager for Blender 3.1

### ISSUE THREAD

**Issue by sgodanas** [ubisoft/shotmanager#22]
**Is your feature request related to a problem? Please describe.**
Blender 3.1 (releasing in March) is switching to Python 3.10.2. Will the add-on be able be compatible (because of the dependency on OTIO)?

Thank you,
Satish.

**Comment by werwack** [comment]
Hi Satish,
I check that tomorrow. Thanks for rising the point.

**Comment by sgodanas** [comment]
No problems. Thank you for looking into it.

**Comment by sgodanas** [comment]
Hi @werwack. Thank you for the update.
Will install the addon for 3.1 and start using it.

**Comment by werwack** [comment]
Hi @sgodanas,
Here it is, at last! Support for Blender 3.1! With OpenTimelineIO and all!
Sorry for the delay, getting the OpenTimelineIO wheels for Python 3.10 was a bit of a challenge for me 😅
So here is [Shot Manager v1.7.16](https://github.com/ubisoft/shotmanager/releases/tag/v1.7.16). Can you give it a try and let me know if you face some issue?
Thank you
