### ISSUE TITLE
Only sometimes Blender doesn't star anymore, until I remove the shotmanager addon

### ISSUE THREAD

**Issue by j2l** [ubisoft/shotmanager#26]
**Infos on the context**
- Add-on version: 2, 0, 102
- Blender version, from installer or from zip: 2.93.3
- OS: Ubuntu 21.10
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): IDK

**Describe the bug**
from console, start blender, see blender closing
`Segmentation fault (core dumped)`

**To Reproduce**
from console, start blender, see blender closing
remove addon, blender stats OK now

**Expected behavior**
blender starting with shot manager :)

I initially thought it was videotrack, https://github.com/ubisoft/videotracks/issues/8
It's not consistent. It happened after I tried to understand shot manager through trial and error.
I would need a quick tuto (in English or French) about  shot manager pipeline, to try to find when the bug happens.

**Comment by werwack** [comment]
Thank you for reporting this issue. It will not be easy for me to fix it since it appears to be OS specific and I cannot test it on Linux.

Can you please do this:
- uninstall Shot Manager and restart Blender
- open the terminal
- install Shot Manager
- Copy all the terminal content and paste it in this conversation

**Comment by j2l** [comment]
Sure, here it is (Stamp INfo already installed):
```
*** *** Registering Ubisoft Stamp Info Add-on - version: 1.3.1  (1003001) - Logger level: INFO *** ***
  Pillow Imaging Library (PIL) correctly installed for Ubisoft Stamp Info

addon_utils.disable: shotmanager not disabled
Modules Installed (shotmanager) from '/home/pm/Downloads/Ubisoft_ShotManager_V2-0-102_Beta.zip' into '/home/pm/.config/blender/2.93/scripts/addons'

*** *** Registering Ubisoft Shot Manager Add-on - version: 2.0.102  (2000102) - Logger level: INFO *** ***

Warning: This script was written Blender version 3.1.0 and might not function (correctly), though it is enabled
```
