### ISSUE TITLE
Installation problem (MacOs Blender 2.93) with 1.5.65 (2021-09-20)

### ISSUE THREAD

**Issue by piotrnikov** [ubisoft/shotmanager#3]
Hi, I can't wait to test this but it's not working on my rig (MbP 16, Macos 11.6). 
It says I'm not connected to Internet... But I am!
<img width="655" alt="Screenshot 2021-09-21 at 07 57 57" src="https://user-images.githubusercontent.com/28474540/134119878-0cbb9052-01e1-4317-bc49-f3746daf7cc4.png">
I tried:
. Starting Blender using sudo /Applications/Blender.app/Contents/MacOS/Blender.
. Using a VPN/turning off firewall.
Nothing works (the ShotManager window is nowhere to be seen).
Any ideas?
Thanks!!

Piotr
EDITED: Works great on my WIN10 rig so it has to do with MacOs I guess.

**Comment by werwack** [comment]
Hi Piotr,
I'll check today. Looks like an OS specific issue indeed. I have no Mac to test. I come back to you asap.

**Comment by piotrnikov** [comment]
@werwack Thanks!
If it's helpful:
. The console doesn't seem to say there is a problem.
. Two other Addons I use (Blender Cloud & Blender ID Authentification) connect to the internet just fine. 
Tell me if I can be of help :)

**Comment by werwack** [comment]
Ok, looks like it is a Certificates issue related to Python 3.7+, the use of the function _urllib.request.urlopen_ and the way Mac browsers work.
See for more: [https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error](https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error)

A solution to this would be to make the add-on install the _certifi_ Python package but I don't find it really clean for the Blender Python environment.
I will remove the internet connexion check for Mac in next version ;)

**Comment by piotrnikov** [comment]
Thanks!

**Comment by werwack** [comment]
@piotrnikov 
Hi Piotr
I've done a similar fix for another add-on, Stamp Info. Have you installed it already?
If not could you please install it on your Mac and tell me if you can do the install successfully?
https://github.com/ubisoft/stampinfo/releases/tag/v1.0.11
You will need this add-on for the full experience of Shot Manager anyway ;)

If you already installed it, well the test to the internet connection will not be done so we'll see on the next release of Shot Manager ;)

Thx

**Comment by piotrnikov** [comment]
@werwack 
Hi!
Yes I've tried installing it and this is the error I have:
<img width="890" alt="Screenshot 2021-09-23 at 11 31 29" src="https://user-images.githubusercontent.com/28474540/134485093-51a3430b-14d9-491c-bff3-403ad60232bc.png">
Oh and I just tried installing that same addon on my Win10 rig and I have the same error...
Dunno if it's helpful...
I'm happy to test more if you want :)

**Comment by werwack** [comment]
Well, yes it is helpful, it means that for some reasons this doesn't work 😅
On Win10 you launched Blender in Admin mode, right?

**Comment by piotrnikov** [comment]
> 

> On Win10 you launched Blender in Admin mode, right?
Oh damn I forgot!
Ok tried installing on Win10 with Blender as admin and I have this error:
![IMG_3843](https://user-images.githubusercontent.com/28474540/134490292-2731bd38-f671-49b3-9984-583e4fa4db72.jpg)

**Comment by werwack** [comment]
Oki, so this error seems to be a backward compatibility issue related to a previous install of the add-on.
If you quit blender and launch it again you will very likely see that everything is ok. Can you confirm this? (like: everything is fine in the Prefs panel?)
Good point is it means the internet connection test works on Mac ;)

Regarding the admin rights... This is a "normal" process when an add-on needs to install some dependencies. Usually you don't see it because most of the addons don't need additional Python libs, but any other addons that do would require such type of launch. somewhat limitative, I admit.

**Comment by piotrnikov** [comment]
Yes you're right!
Everything works fine on Blender 2.93 (Win10 & MacOs).
On Blender 3.0 Alpha I'm still getting this error whatever I do. I know it's early days but I thought I'd report it nonetheless :)

<img width="646" alt="Screenshot 2021-09-23 at 13 06 46" src="https://user-images.githubusercontent.com/28474540/134496867-4e52c0b8-ee48-43d0-9bb6-bb58513ecdfa.png">

Thanks for the explanation and it makes sense!

**Comment by werwack** [comment]
Oki, I haved tested on 3.0 A but that's something I fixed already.
So next step is Shot Manager :)

**Comment by piotrnikov** [comment]
Oops sorry! Everything is working on Win10 + Blender 3.0 Alpha.
Only the MacOs version spits out that error message. Sorry for the confusion.

**Comment by werwack** [comment]
New release on Stamp Info, hopefully fixing your 3.0A Mac version ;)
https://github.com/ubisoft/stampinfo/releases/tag/v1.0.12

**Comment by piotrnikov** [comment]
It totally works!!!!!!
Bravo and thanks :)

**Comment by werwack** [comment]
Great, thanks a lot to you for your help!

**Comment by werwack** [comment]
@piotrnikov 
Here it is, I published the version of Shot Manager. Let me know if something is wrong on your platforms ;)

**Comment by piotrnikov** [comment]
Yes I saw, it works great thanks so much!!! I just need to copy all my settings to admin (addons & preferences), but that shouldn't be an issue. Thanks again!

**Comment by piotrnikov** [comment]
It's me again sorry! I'm having an issue with where Blender config files are stored when I launch Blender in admin mode. It (Blender) seems to create a new environment at this location /var/root/Library/Application Support/Blender/3.0/, which I cannot access. The usual location for config files on Mac is this one /Users/piotrnikov/Library/Application Support/Blender/3.0.
It's a problem if I want to copy my old setup (from my account) to this new one (admin).
Also, and you may already know this, I get this error message when trying to render an image from StampInfo:
<img width="906" alt="Screenshot 2021-09-24 at 05 45 59" src="https://user-images.githubusercontent.com/28474540/134615213-16cc87a8-c20a-4602-a0ff-bd2128756aad.png">
ShotManager on the other hand seems to be working just fine (from my very limited knowledge of the addon :)

**Comment by werwack** [comment]
_ShotManager on the other hand seems to be working just fine (from my very limited knowledge of the addon :)_
Ok, so I close this issue :)

I move the other issue and your question there:
https://github.com/ubisoft/stampinfo/issues/2

**Comment by werwack** [comment]
Fixed on SM 1.5.66
