### ISSUE TITLE
audio waveform and grab strips

### ISSUE THREAD

**Issue by j2l** [ubisoft/shotmanager#31]
The duration of shots usually follows the audio rhythm. 
Audio plays when previewing shots but, setting a shot precise duration before preview would be great!

Also I need to be able to grab strip (shot) start and end (like in video editing), without entering start and end frame numbers in the shot list, since, as soon as you manually enter a number, it also move the play head to the start of the shot (so you have to memorize the end frame, then enter it in the shot list

**Describe the solution you'd like**
a Sequencer like strip above shots, or simply a button to open and scale the sequencer (zoom on first track, same time window as timeline) 

**Describe alternatives you've considered**
Add Sequencer, zoom track and time manually, but no strip grab, play head always moving back to shot start frame:
![image](https://user-images.githubusercontent.com/65325/174987408-f7736b00-c17e-40c1-bfc0-b4e8ad71178b.png)

EDIT: Hmm, looking at your video, I guess audio was added in post-prod since the back in time ellipse didn't break the audio.
Wouldn't it be nice to also be able to play the audio linearly while jumping in time? 
I know it's far beyond shot manager since we only have one line of time in a scene in Blender.
Maybe if shots could populate VSE once a sequence is validated?

EDIT2: I tried to do the post-prod in Blender (I did my short film with Blender). Actually, your pipeline breaks the Blender internal way of editing a sequence which is:
create a new scene (empty)
go to VSE tab
Add > sound
Add > scene > first scene
select strip > N > define camera and duration of the strip
duplicate the strip
move strip on timeline
change camera and time offset for ellipses

J'devrais p'tet venir chez Ubi ? :smile_cat:

**Comment by werwack** [comment]
"Actually, your pipeline breaks the Blender internal way of editing a sequence"...
Actually it introduces another way of working. It does this by allowing a non linear editing of the sequence, leveraging the flexibility of filming the content of a scene.
By using the VSE in the scene you are bound to be linear and you miss the point of Shot Manager.

I perfectly recognize that this may not be easy to get at the beginning since I haven't done many tutorial videos so far, but I recommend you have a look at this one: https://www.youtube.com/watch?v=btLygAlD41c

**Comment by werwack** [comment]
@j2l Questions: It looks like you are using Blender 2.93.3 right?
Are you bound to this version?
Since 2.93 is a LTS, could you consider switching to the latest release (2.93.10 I guess)? That would ensure the bugs you mentioned are as little as possible coming from Blender.

**Comment by j2l** [comment]
deb doesn't exist beyond 2.93.3 :(
the snap version (3.2.0) can't install dependencies because it's snap, haaa.
So yeah, I'm stuck with 2.93.3 until they update it.
