### ISSUE TITLE
Shots Play mode resets on shots with start frames set on 0

### ISSUE THREAD

**Issue by tonpix** [ubisoft/shotmanager#35]
**Infos on the context**
- Add-on version: 2.0.102
- Blender version, from installer or from zip: 3.2 installed
- Blender was launched in Admin mode? no
- OS: windows 10
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): I don't know

**Describe the bug**
Playback resets once it hits shot with start frame 0

**To Reproduce**
1. create 3 shots
2. first 2 shots start frames on 1 or higher
3. 3rd shot on start frame 0

You will notice when addon is supposed to play shot1->shot2->shot3, it keeps looping on shot1->shot2, skipping shot3 entirely. Setting shot3 start frame on 1 or higher fixes it

Video clip: https://files.catbox.moe/rbfdhg.mp4

**Comment by werwack** [comment]
Hi @tonpix ,
Thank yo for the report. I get an eye at it.
