### ISSUE TITLE
Render progress bar + GPU engine cycles

### ISSUE THREAD

**Issue by halasox** [ubisoft/shotmanager#37]
Add a progress bar for rendering in the SM-render and add selection for cycles GPU engine.

**Comment by werwack** [comment]
Hi @halasox,
yes, a progress bar would be very useful indeed :)
It is a pity there is no such a widget by default in Blender. I worked on it a long time ago but the results were not satisfying.
Now I have a better idea on how this can be done and I'm just looking for time to implement it. There is some refactor to be done in the rendering loop though.
According to the current to do list I think this should come around September, hardly before I'm afraid...

Regarding the GPU engine for Cycles that's something to investigate. I'll let you know asap.

**Comment by halasox** [comment]
Hi @werwack 

First of all thanks for creating such amazing and useful addon that's free for all! Great you found a way with the progress bar 😄. For the gpu engine as you can see from the image I have selected from scene, the other two options are workbench and evee. However, when I use from scene and cycles is set it gives me a black image!

![image](https://user-images.githubusercontent.com/10233586/180603554-b3dda705-d940-4de4-b98f-3721cf364fcb.png)
