### ISSUE TITLE
Adding Markers to Retimer

### ISSUE THREAD

**Issue by rbergeron3d** [ubisoft/shotmanager#38]
Hello! 
I've just discovered the Shot Manager and as a Previs Artist, and it rocks!!!
I was wondering if it was possible to add a checkbox for the Selected Markers in the Retimer. I am thinking of exploring more the Shot Management method in the near future, but for now dealing in really heavy scenes, it seems that the timeline Camera markers solution is still ideal to keep going at 24 fps.

Let me know what you think :)

Ray

**Comment by werwack** [comment]
Hi @rbergeron3d 
By mentioning this checkbox for markers in the Retimer you just put the finger on a fix/feature that I have to do for a long time but... well, wasn't a really high priority so far. So I'll raise it in the roadmap.
If you are interested in dealing with markers I developed a very cool tool to navigate in long sequences with hundreds of markers. You can see it [on the screenshot of VideoTracks](https://github.com/ubisoft/videotracks/blob/main/doc/images/VideoTracks_screen.png), it's the arrow buttons and the filter field on the VSE toolbar.
I'm not sure this Video Tracks add-on is still working but I planned to get that tool back to Shot Manager soon.

Regarding the framerate of the play, I mean the real time play in the viewport, Shot Manager is not so greedy. The performances mainly depends on the scene content. So Shot Manager or markers, should more or less be the same. Except that in Shot Manager there is a Playblast render feature if you need to ;)

I'll post here the version of SM integrating the marker fixes.

**Comment by werwack** [comment]
Hi @rbergeron3d,
In the pre-release version I just pushed there is the support of the markers in the Retimer tool :)
I also added the tool I mentioned above. It is called Markers Nav Bar and you can enable it in the Features panel of Shot Manager.
https://github.com/ubisoft/shotmanager/releases/tag/v2.0.224

Let me know what you think ;)
