### ISSUE TITLE
'Render current' always uses 'Use Stampinfo' even if unchecked

### ISSUE THREAD

**Issue by Gattung** [ubisoft/shotmanager#4]
Hello thanks for this amazing tool!

When I use 'Render Current' and uncheck 'Use Stampinfo' it will always use stampinfo for the render for the first render. if I uncheck it and render again it will render correctly and not use stampinfo.

Thanks!

**Comment by Gattung** [comment]
I am using 1.5.66  with Blender 3.0 alpha. I just tried it in Blender 2.93 and it is working fine there so I guess its unnecessary to try to fix until B3.0 is released. 

Thanks

**Comment by werwack** [comment]
Fixed on [V 1.7.10](https://github.com/ubisoft/shotmanager/releases/tag/v1.7.10).
Let me know if you still have the issue.
