### ISSUE TITLE
插件运行不了

### ISSUE THREAD

**Issue by sanroot3** [ubisoft/shotmanager#40]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 371, in enable
    mod.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\shotmanager\__init__.py", line 100, in register
    utils_ui.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\shotmanager\utils\utils_ui.py", line 377, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'UAS_ShotManager_OpenExplorer'

**Comment by sanroot3** [comment]
您好，我在Blender中安装好插件后却启动不了

**Comment by werwack** [comment]
Hello @sanroot3,
Indeed this message can appear. I guess it is at install time. This is due to a conflict with the add-on Ubisoft Stamp Info.
If you restart Blender then Shot Manager should work fine anyway.
If you have Stamp Info installed then you can remove it, it is now provided with Shot Manager V2.

Let me know if you are still stuck. Please provide more info on the context ;)

Julien

**Comment by sanroot3** [comment]
我没有安装 Ubisoft Stamp Info ，我3.2 3.1 2.9 三个版本都尝试过仍然会出现BUG无法启动[](url)

**Comment by sanroot3** [comment]
每次初次启动时出现的错误Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\shotmanager\__init__.py", line 150, in register
    installErrorCode = install_dependencies([("PIL", "pillow")], retries=1, timeout=5)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\shotmanager\install\install_dependencies.py", line 204, in install_dependencies
    addon_error_prefs.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\shotmanager\install\addon_error_prefs.py", line 138, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'UAS_ShotManager_AddonErrorPrefs'

**Comment by sanroot3** [comment]
I have not installed Ubisoft Stamp Info, I have tried all three versions 3.2, 3.1 and 2.9, and still there will be a BUG that cannot be started

**Comment by werwack** [comment]
Thanks for the additional log messages. I'll check with that.

**Comment by sanroot3** [comment]
Good work, hope it will be resolved soon

**Comment by sanroot3** [comment]
Hello, version 2.0.102, I can install,
I seem to have found the reason why version 2.0.214 cannot be installed. It may be that Stamp Info is integrated. I tried to install Stamp Info separately without success
![b4ab673172ac327ed49608d91252ed7](https://user-images.githubusercontent.com/111350002/186185953-b2bc4bd1-b634-41de-9ecb-17e6e2b9767c.png)
![aa483d11de6760806d077157136526d](https://user-images.githubusercontent.com/111350002/186186137-d5fcf0f7-0dbc-4503-a2c8-70f7afbfa696.png)
![3b1182ed5704f8d90d726fc4587d009](https://user-images.githubusercontent.com/111350002/186186170-3c2d33aa-ad69-4a8f-9568-eaec406d5923.png)
.

**Comment by werwack** [comment]
Hi @sanroot3,
I just pushed a new pre-release version with a fix for the error you get at install time. Can you try with this version please?
https://github.com/ubisoft/shotmanager/releases/tag/v2.0.224

Also be sure to respect the installation conditions, they are important:
https://ubisoft-shotmanager.readthedocs.io/en/latest/getting-started/install.html

**Comment by sanroot3** [comment]
![1662797485449](https://user-images.githubusercontent.com/111350002/189475021-1698776c-9a32-4b54-8f79-c3e87167b205.png)
installed, thanks a lot

**Comment by sanroot3** [comment]
It is installed in administrator mode and the network is connected normally.

**Comment by werwack** [comment]
Geeh... Well I don't know why you don't have the extensions installed then.
If you really want them you may try this:

-     go to the directory of Blender where all the Python packages are installed (should be something like this: C:\Program Files\Blender Foundation\Blender 3.2\3.2\python\lib\site-packages )

-     delete the folders related to opentimelineIO (namely opentimelineio, opentimelineio_contrib, OpenTimelineIO-0.15.0.dev1.dist-info and opentimelineview - basically everything starting with opentimeline). Note that they may have been installed in an other Python location if you have Python installed (something like C:\Users\<your name>\AppData\Roaming\Python\Python310\site-packages for instance)

-     Re-do the install process (Blender in Admin mode, install, quit, relaunch in normal mode).

And then let me know ;)

**Comment by sanroot3** [comment]
![1664280196319](https://user-images.githubusercontent.com/111350002/192520186-168f14b3-cb75-4f94-b92d-6db50537232e.png)
![1664280204923](https://user-images.githubusercontent.com/111350002/192520202-fd0d4af8-57da-4217-b8e9-6654e6968e8b.png)
Folders related to opentimelineIO not found
