### ISSUE TITLE
Toggle Overlay Tool Display not working on MacOs (Silicon) - Works as intended on Win10-11

### ISSUE THREAD

**Issue by piotrnikov** [ubisoft/shotmanager#45]
**Infos on the context**
- Add-on version: V2-0-225
- Blender version, from installer or from zip: 3.4 Alpha
- Blender was launched in Admin mode? Yes
- OS: MacOs 12.6 (Apple Silicon)
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): Don't know. Works on Win10-11

**Describe the bug**
Toggling Overlay Tool Display works fine in Timeline Window but not in DopeSheet/GreasePencil on MacOs (Silicon).

**To Reproduce**
1. Create Shot.
2. Toggle Overlay Tool Display
3. No overlay appear in Grease Pencil DopeSheet. 

**Expected behavior**
See Overlay

**Screenshots**

https://user-images.githubusercontent.com/28474540/191214404-9081817f-2335-49d3-9596-cdc21094227c.mp4

**Additional context**
I tried resetting my preferences and still have the issue.

**Comment by werwack** [comment]
Hi @piotrnikov,
Appart from the fact that you are running on an alpha - so a not supported version of Blender (see [my answer here](https://github.com/ubisoft/shotmanager/issues/46) about it), this behavior seems to be normal. Thanks for the video btw, that really helped me getting your point.

So, as you said, you are expecting the Shots Stack (= the overlay display of the shots in a time editor) to appear in the Dopesheet when pressing the Overlay Toggle button. Do do so there are a few things to know there:

- there can be only one Shots Stack displayed at a time in a workspace context. Meaning if you have several Timeline editors and several Dopesheets you have to specify which one will receive the Shots Stack. (Shots Stack can be displayed only over those 2 kinds of editor windows).

- By default the Shots Stack appears on the Timeline with the lower index in the list of Timeline editors.

- To specify on which editor (= target) you would like to see the Shots Stack displayed, open the Shots Stack Settings dialog window (5th button on the right from the Toggle Display Overlay one on the Timeline toolbar). The first option is called Target Dopesheet Editor. Click on the button on the right to identify the various opened Dopesheed, then set the index of the one you want in the dropdown list. This will stay stored in the scene.

I'll try to complete the doc for that asap.

I hope that helps, let me know if you have more questions.

**Comment by piotrnikov** [comment]
Aahhhhhh ok!
The target thing is a bit obscure but makes sense and it works. Thanks so much for explaining!

**Comment by werwack** [comment]
Well, it is a bit advanced, and obviously needs some documentation.
You have the same thing for the 3D viewport: if you want to have the Shot Manager panel on one viewport and all the related actions (camera changing, Sequence Timeline overlay...) on another, you can change the target viewport index in the dropdown that is place on the right of the sequence name, in the main Shot Manager panel.

**Comment by piotrnikov** [comment]
Oh that's so great!!
