### ISSUE TITLE
Converting to Markers for Render Farm (or other way to do so)

### ISSUE THREAD

**Issue by pesjakves** [ubisoft/shotmanager#47]
Hello, me again. 
I am looking for a way to use Shot Manager with Render Farms.
So far, I did not come up with a way to do it as I cannot get the addon to render farms' machines.
One way I came up with would be 
- converting the shots to Markers and Camera Binding (of course, shots cannot overlap then)
- or exporting each Shot into individual Blender files (very painful)

The first method seems a bit easier and I hope it would not mess things up that much :)
Is there a way to convert Shot Manager shots to Markers with Camera Binding?

Thank you for your work !

Best regards

Mikoláš

**Comment by pesjakves** [comment]
I hope I might use Barista as it works more like a remote desktop on Amazon servers from what I understood, but I am still not sure :)  https://blendermarket.com/products/barista

**Comment by pesjakves** [comment]
Hi @werwack,

Thank you for all the info! I would really appreciate the solution you proposed. I myself am probably not capable of writing such script and switching to the other Shot Manager would definitely be a bit tedious at the moment :) Would you be so kind and help me write the rendering script? 

For the general usecase, I think that the UbiSM would really benefit some kind of a pipeline solution that would allow for something else then local rendering. Perhaps Flamenco integration would be possible in the future? 
This would greatly expand possibilities for many small Blender studios like mine, where we dont have any developer on the team. I understand that the addon's purpose right now is more about layout and storyboarding, not "final rendering".

Of course, this is my first project with UbiSM, so I probably dont fully comprehend your development decisions just yet :)

**Comment by werwack** [comment]
At the moment the architecture of the rendering is not made **at all** for distributed rendering. Indeed the final image of each shot is a composition of a rendering and a frame with the stamped info. Considerable work has to be done to change the approach.

Regarding the script to create the markers from the shots, it is available in the latest beta version: [v2.1.24_Beta](https://github.com/ubisoft/shotmanager/releases/tag/v2.1.24_Beta). 
Install this version then get the script from here (more convenient): 
https://github.com/ubisoft/shotmanager/blob/main/shotmanager/api/api_code_samples/api_export_shots_to_markers.py

To run it, once your project file is opened in Blender, go to the Scripting workspace and load that Python file in the editor. Then just press on the Run Script (button with the arrow on the right of the editor toolbar).
