### ISSUE TITLE
Splitting a Shot in Two

### ISSUE THREAD

**Issue by pesjakves** [ubisoft/shotmanager#49]
Hi its me again with some feedback!

It would be very useful to be able to Split a Shot at the Current Frame (maybe even with a shortcut or a button in the dopesheet). 
The Icon could sit there together with the New Shot and Duplicate Shot buttons.
![image](https://user-images.githubusercontent.com/53349108/195584685-4a4a6775-0f64-4739-89d1-3bec03f5778a.png)
The Split Shot might also follow some naming rules (f.e, a shot number 1 would be split into 1a and 1b). 
I hope this feedback proves useful!

Best Regards 

Mikoláš

**Comment by werwack** [comment]
Hi @pesjakves ,
This is a cool idea :)
I put it in the backlog. no ETA though, priority for the moment is stabilizing the workflow.
