### ISSUE TITLE
NB. pip install of otio whl is now working for 2.93 on Windows

### ISSUE THREAD

**Issue by tin2tin** [ubisoft/shotmanager#5]
It is now possible this way:
`python -m pip install -i https://test.pypi.org/simple/ jcmorin-OpenTimelineIO==0.14.0.dev5`

https://github.com/PixarAnimationStudios/OpenTimelineIO/pull/1110

**Comment by werwack** [comment]
Hi @tin2tin 
Thank you very much for the tip!
I had a quick look at your proposition but it is a bit obscure to me. Could you please provide more details on the path to get the package?
Does this work for any plateform?

In the mean time a work mate made a wheel for OpetimelineIO v0.13 for Windows. I integrated it in the [release SM 1.5.73](https://github.com/ubisoft/shotmanager/releases/tag/v1.5.73) and it seems to work, so far.
May you have some feedback or ideas to improve this it is also very welcome.

**Comment by tin2tin** [comment]
I just wanted to share the good news, that the otio folks are getting closer to releasing a whl which will work on Blender 2.93 and Win, but it's not an official release yet.

You current release also works here. Great. Thank you.
