### ISSUE TITLE
Black screens instead of rendering out.

### ISSUE THREAD

**Issue by lokeyftw** [ubisoft/shotmanager#50]
**when i try to playblast or anything else it comes out as just black with no video**
- Add-on version: [V 2.1.32]
- Blender version, from installer or from zip: 3.3.0
- Blender was launched in Admin mode? yes
- OS: windows 11
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x):  idk

**Describe the bug**
when i try to playblast or anything else it comes out as just black with no video

**To Reproduce**
1. Go to '...' try to playblast idk

**Expected behavior**
render out as a video

**Screenshots**
![image](https://user-images.githubusercontent.com/116744060/198071669-eca17405-df78-4e0a-b65b-0e7719596166.png)

**Additional context**

**Comment by jatubi** [comment]
Hi @lokeyftw 
According to the information you provided you are running SM in admin mode. This should append only when you install SM, to allow th Python dependencies to be installed. Once this is done, Blender should be launched in normal mode.

Admin mode can have a lot of drawback effects, as possibly some rendering issues.

Let us know if you have the same issue in normal mode. And if it is the case can you please copy all the log that appears in the Blender terminal and send it to us?

Thank you

**Comment by lokeyftw** [comment]
yeah that worked thanks
