### ISSUE TITLE
1.5.73 OpenTimelineIO "Module not found"

### ISSUE THREAD

**Issue by Gattung** [ubisoft/shotmanager#6]
This is the error I get under 'Dependencies' when installing in Blender 2.93 and 3.0 alpha.
Otherwise it installs ok and seems to work.

I install in admin mode in both cases. I also remove previous version. 

Love the new camera to view, such a time saver!

**Comment by werwack** [comment]
That's weird if you are in Admin mode.
Can you tell me if you are using an installed version of Blender or an unzziped one? On which plateform?
Where do you get this error, in the console I guess? Can you copy here the content of the console after the launch of Blender (or after the check of the Install checkbox of the addon)?

Also I set up some templates to enter bugs, they have all those questions listed, that considerably facilitate the support here so if you could use them.

I'm glad you like the camera view match :) I'm considering letting this behavior all the time and removing the checkbox, what do you think? Not sure the old behavior is really something we want to keep.
Btw this camera to view is also available as a tool for any camera, without shot creation:
![image](https://user-images.githubusercontent.com/15678244/138036049-59e1ef6a-1c2d-4ff0-b780-91844609eb2c.png)

**Comment by Gattung** [comment]
- Addon Ver: 1.5.73
- Blender version, 2.93.3 installed version and 3.0 alpha zipped version
- Blender was launched in Admin mode? Yes
- OS: Windows 10

**Describe the bug**
When installing the addon OpoenTimelineIO fails to install

![2021-10-20](https://user-images.githubusercontent.com/244226/138142965-e66a1dd1-92a6-497e-b472-7bd164a16655.png)

Yes! I think making it the default behavior of camera to view makes a lot of sense.

**Comment by werwack** [comment]
Hi Gattung,
I appologize for the late answer. Thank you for the feedback.
I also notices some install issues on my site. An official wheel package has been released not long ago, I will switch the code to use it.
The fix will be part of the release of the version 1.6

**Comment by werwack** [comment]
Fixed on SM 1.6.9
