### ISSUE TITLE
'bl_info' gives bad performance.  Constant error running and big fps drops with Shot manager overlay on

### ISSUE THREAD

**Issue by SpitfireStoryboards** [ubisoft/shotmanager#7]
**Infos on the context**
- Add-on version: 1.5.72
- Blender version, from installer or from zip: 2.93.5
- Blender was launched in Admin mode? Yes
- OS: Win10

**Describe the bug**

When I have the addon installed, I have a constant stream of : fake module : addon missing 'bl info' gives bad performance! It runs constantly as an error. Further to this, when I activate the visual overlays for the timeline for the addon, I get a between 5 -20fps drop in performance.

**To Reproduce**
1. Go to ' switch on overlays'
2. Click on 'play'
3. Scroll down to 'look at fps counter'

**Expected behavior**

To not have a fps drop on playback and not have the error constantly running

**Screenshots**
![ScreenHunter 1532](https://user-images.githubusercontent.com/93609018/139912712-6c00d84a-5e1c-4c2c-a11b-57094d468725.png)
![ScreenHunter 1534](https://user-images.githubusercontent.com/93609018/139913368-2a625a1e-9ee9-4baa-9072-6fb1f9c29e51.png)
![ScreenHunter 1533](https://user-images.githubusercontent.com/93609018/139913376-63aac02e-b5f7-4732-8c01-984e81adee1d.png)
![InkedScreenHunter 1536_LI](https://user-images.githubusercontent.com/93609018/139913378-f037ec27-ccb4-4900-9ae2-2de0e89dbf4d.jpg)
![InkedScreenHunter 1535_LI](https://user-images.githubusercontent.com/93609018/139913384-c9f6e0da-f0e7-4b33-87ee-3a414793c3d0.jpg)

**Additional context**

**Comment by werwack** [comment]
Thanks for the repport.
So there are 2 things:

- The messages in the log are coming from an add-on that is not part of Shot Manager. You very likely installed VF-BlenderAutoSaveRender from [https://github.com/jeinselenVF/VF-BlenderAutoSaveRender](https://github.com/jeinselenVF/VF-BlenderAutoSaveRender). I don't know why but it looks like there is a possible incompatibility here. I had a quick look at this add-on. Do you really need it now with Shot Manager? If so, why? What does it do exactly?

- There is indeed a framerate drop when we play with the opengl overlay activated. I'm investigating it to see if some optimizations could be done there. Turnaround is to turn off the display when playing (not sure at all I can do that automatically in code as far as I see)

**Comment by SpitfireStoryboards** [comment]
Hi Werwack

Thanks for the response

I have never used that addon , and it is not installed on my system.

Unless it is now part of blenders build and not an addon anymore? 

I searched addons and there is nothing of that name there. And I checked my addons folder and also not there

**Comment by werwack** [comment]
That's strange, it appears in the log of your screenshots, and I don't have it in my version of Blender.
Could it be an add-on that was used before with the Blender file you are working on (or used by someone before you and the file keeps a reference to it maybe?)?
And do you have this message all the time? With every .blend files?

**Comment by werwack** [comment]
So I added a new "Best Play Performance" mode in the UI to disable the overlay tools (timelines and shots stack) that were kind of greedy during the animation play. This is in version 1.5.74, released soon.
Still have to add the documentation for it at some point.

**Comment by werwack** [comment]
Fixed on SM 1.6.9
